### ISSUE TITLE
CovidCode no longer depends on KeyCode

### ISSUE THREAD

**Issue by marado** [stayawayinesctec/dp3t-docker#2]
CovidCode no longer depends on KeyCode, so (AFAICS) there is no reason to provision KeyCode on this dp3t-docker project.

**Comment by jopereira** [comment]
KeyCloak was initially used for two purposes: 1) generating JWTs that are sent to the app and backend; and 2) as an oath2 provider for health care professionals. Although it is true that reason 1 no longer applies, we still need it for reason 2, at least for a complete self-contained test deployment. It might be removed in production, if some other existing provider is used.
