### ISSUE TITLE
Login Credentials

### ISSUE THREAD

**Issue by echosalik** [stayawayinesctec/dp3t-docker#4]
What are the login credentials and where are they stored?
I tried using `admin` and the password in the secrets file but it says auth failed. Any direction would be helpful.

Regards

**Comment by jopereira** [comment]
The admin user works only in the admin console (master realm). It is not exposed in the "public" https server on port 443.

To access it in the default docker compose configuration connect to http://localhost:8180 and select the "Administration Console" option. The admin user should be accepted there.

Let me know if this fixes the problem.

**Comment by echosalik** [comment]
Thank you that did it 👍
